import Head from 'next/head';
import {
  styled,
  css,
  useTheme,
  configTheme,
  globalCss,
} from '../../../../theme';

const Container = styled('div', {
  width: '100vw',
  height: '100vh',
  display: 'flex',
  flexDirection: 'column',
  backgroundColor: '$backgroundColor',
});

const Main = styled('main', {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  '& > div': {
    minWidth: 500,
    minHeight: 500,
    padding: 20,
    borderWidth: 1,
    borderColor: '$gray100',
    borderStyle: 'solid',
    borderRadius: 6,
    backgroundColor: '$white',
  },
});

const Header = styled('header', {
  width: '100vw',
  display: 'flex',
  justifyContent: 'flex-end',
  alignItems: 'center',
  paddingTop: '1.5rem',
  paddingRight: '1.5rem',
  paddingBottom: '1.5rem',
});

const globalStyles = globalCss({
  '*': { margin: 0, padding: 0 },
});

const Button = styled('button', {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: '$small',
  border: 'unset',
  cursor: 'pointer',
  transition: '0.8s',
  '&:hover': {
    opacity: 0.8,
  },
  variants: {
    color: {
      success: { backgroundColor: '$green', color: '$white' },
      info: { backgroundColor: '$teal', color: '$white' },
      warning: { backgroundColor: '$warning', color: '$white' },
    },
    size: {
      small: {
        height: 45,
        width: 160,
        fontSize: 14,
        fontWeight: 500,
      },
      medium: {
        height: 48,
        width: 216,
        fontSize: 14,
        fontWeight: 500,
      },
      large: {
        height: 48,
        width: 235,
        fontSize: 14,
        fontWeight: 500,
      },
    },
    outlined: {
      true: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderStyle: 'solid',
        '&:hover': {
          color: '$white',
        },
      },
    },
  },
  compoundVariants: [
    {
      color: 'success',
      outlined: true,
      css: {
        color: '$green',
        borderColor: '$green',
        '&:hover': {
          backgroundColor: '$green',
        },
      },
    },
    {
      color: 'info',
      outlined: true,
      css: {
        color: '$teal',
        borderColor: '$teal',
        '&:hover': {
          backgroundColor: '$teal',
        },
      },
    },
    {
      color: 'warning',
      outlined: true,
      css: {
        color: '$warning',
        borderColor: '$warning',
        '&:hover': {
          backgroundColor: '$warning',
        },
      },
    },
  ],
  defaultVariants: { color: 'success', size: 'small' },
});

const Text = styled('p', {
  fontFamily: '$untitled',
  color: '$gray',
  variants: {
    size: {
      1: {
        fontSize: '$1',
      },
      2: {
        fontSize: '$2',
      },
      3: {
        fontSize: '$3',
      },
    },
    teste: {
      true: { color: '$teal' },
    },
  },
});

const Home = () => {
  const { changeTheme, theme } = useTheme();
  const teste = css('h1', { color: '$teal' });
  console.log(configTheme.theme.colors.teal);

  function handleChangeTheme() {
    changeTheme();
  }
  globalStyles();
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Button
          type="button"
          size="small"
          color="info"
          onClick={handleChangeTheme}
        >
          Tema {theme === 'light' ? 'Light' : 'Dark'}
        </Button>
      </Header>
      <Main>
        <div>
          <Text as="h3" size="3">
            Hello, from Stitches.
          </Text>

          <h1 className={teste()}>TEste</h1>
        </div>
      </Main>
    </Container>
  );
};

export { Home };
